development:
  host: localhost
  database: generic_rails_project_development

test:
  host: localhost
  database: generic_rails_project_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>


allow_dynamic_fields: false
