development:
  host: localhost
  database: marcin_k_cebula_development

test:
  host: localhost
  database: marcin_k_cebula_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>


allow_dynamic_fields: false
